'use strict';

/* One menu for every jtees.net page.
 *
 * The site's pages are plain HTML, and each had grown its own copy of the
 * header: the homepage, the service/area pages and the blog all showed
 * different menus (2026-10). The menu now lives in one file,
 * public/assets/data/site-nav.json, and this script writes it into every page
 * between two markers. Styles and behaviour live in their own files
 * (assets/css/site-nav.css, assets/js/site-nav.js) with `jtn-` class names, so
 * no page's own CSS can restyle it.
 *
 * It also places the review strip (assets/js/review-strip.js) above the footer.
 *
 *   node tools/site-nav.js --write   rewrite every page from site-nav.json
 *   node tools/site-nav.js --check   list pages whose menu has drifted (exit 1)
 *
 * The first --write on a page also removes its old announcement bar, header and
 * mobile drawer. tests/site-nav.test.js runs --check.
 */

const fs = require('node:fs');
const path = require('node:path');

const PUBLIC = path.join(__dirname, '..', 'public');
const NAV = path.join(PUBLIC, 'assets', 'data', 'site-nav.json');
const START = '<!-- site-header:start — generated by tools/site-nav.js from assets/data/site-nav.json; edit that file, not this block -->';
const END = '<!-- site-header:end -->';
const CSS_TAG = '<link rel="stylesheet" href="/assets/css/site-nav.css" />';

/* The review strip, above the footer on every page but these: the homepage
   has the full Reviews section, and a 404 should get the visitor moving. */
const RS = '<!-- review-strip:start — generated by tools/site-nav.js -->';
const RE = '<!-- review-strip:end -->';
const REVIEWS_BLOCK = `${RS}
<div id="jt-reviews"></div>
<script src="/assets/js/review-strip.js" defer></script>
${RE}`;
const REVIEW_CSS_TAG = '<link rel="stylesheet" href="/assets/css/review-strip.css" />';
const NO_REVIEWS = new Set(['index.html', '404.html']);

/* Pages that carry the site menu. sms-terms and the printable price sheet are
   standalone documents and keep no site chrome. */
const SKIP = new Set(['sms-terms.html', path.join('downloads', 'big-head-cutout-pricing.html')]);

function pages() {
  const out = [];
  (function walk(dir) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { if (e.name !== 'assets') walk(p); continue; }
      const rel = path.relative(PUBLIC, p);
      if (e.name.endsWith('.html') && !SKIP.has(rel)) out.push(rel);
    }
  })(PUBLIC);
  return out.sort();
}

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const ICON = {
  ig: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.2c3.2 0 3.6 0 4.8.1 3.3.1 4.8 1.7 4.9 4.9.1 1.3.1 1.6.1 4.8s0 3.6-.1 4.8c-.1 3.2-1.7 4.8-4.9 4.9-1.3.1-1.6.1-4.8.1s-3.6 0-4.8-.1c-3.3-.1-4.8-1.7-4.9-4.9C2.2 15.6 2.2 15.2 2.2 12s0-3.6.1-4.8C2.4 3.9 3.9 2.4 7.2 2.3 8.4 2.2 8.8 2.2 12 2.2zm0 3.6a6.2 6.2 0 1 0 0 12.4 6.2 6.2 0 0 0 0-12.4zm0 10.2a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.4-11.8a1.4 1.4 0 1 0 0 2.9 1.4 1.4 0 0 0 0-2.9z"/></svg>',
  phone: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 1C7 1 3 5 3 10v7c0 1.7 1.3 3 3 3h3v-8H5v-2c0-3.9 3.1-7 7-7s7 3.1 7 7v2h-4v8h3c1.7 0 3-1.3 3-3v-7c0-5-4-9-9-9z"/></svg>',
  cart: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm10 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zM5.2 4l.9 2H20a1 1 0 0 1 .9 1.4l-3.3 6A2 2 0 0 1 15.9 14H8.1l-1 1.8V16h12v2H7a2 2 0 0 1-1.8-2.9l1.4-2.5L3 4H1V2h3.3l.9 2z"/></svg>',
  user: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4.4 0-9 2.2-9 5v3h18v-3c0-2.8-4.6-5-9-5z"/></svg>',
  text: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zM7 9h10v2H7V9zm6 5H7v-2h6v2zm4-6H7V6h10v2z"/></svg>',
};

/* `site` is '' for jtees.net's own pages (links stay relative) and
   'https://www.jtees.net' for the snippet the Design Studio shows, where every
   jtees.net link and asset must be absolute. */
function render(nav, site = '') {
  const abs = (h) => (site && h.startsWith('/') ? site + h : h);
  const link = (i, cls) => `<a href="${esc(abs(i.href))}"${cls ? ` class="${cls}"` : ''}${/design\.jtees\.net/.test(i.href) ? ' data-from="nav"' : ''}>${esc(i.label)}</a>`;
  const desk = nav.menu.map((m) => m.items
    ? `<div class="jtn-dd"><button type="button" class="jtn-dd-t" aria-expanded="false">${esc(m.label)}</button><div class="jtn-dd-m">${
        m.items.map((i) => link(i, i.strong ? 'jtn-strong' : '')).join('')}</div></div>`
    : link(m)).join('\n      ');
  const drawer = nav.menu.map((m) => m.items
    ? `<details><summary>${esc(m.label)}</summary>${m.items.map((i) => link(i, i.strong ? 'jtn-strong' : '')).join('')}</details>`
    : link(m)).join('\n    ');
  const bar = nav.announcement.map((a) => a.href ? `<a href="${esc(abs(a.href))}">${esc(a.text)}</a>` : esc(a.text)).join(' <span aria-hidden="true">|</span> ');
  const tel = `tel:${nav.phone.tel}`;
  const sms = `sms:${nav.phone.tel}?&body=Hi%20June%27s%20Tees!%20I%20have%20a%20question%20about%20a%20custom%20order.`;
  const head = site ? `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" />
<link rel="stylesheet" href="${site}/assets/css/site-nav.css" />
` : '';
  return `${START}
${head}<div class="jtn-bar">${bar}</div>
<div class="jtn" role="banner">
  <div class="jtn-in">
    <a href="${abs('/')}" class="jtn-logo"><img src="${abs('/assets/images/brand/logo-mark.png')}" alt="June's Tees &amp; Things logo" width="40" height="44" /><span>June's Tees &amp; Things<small>Chicago Custom Printing</small></span></a>
    <nav class="jtn-menu" aria-label="Main">
      ${desk}
    </nav>
    <div class="jtn-act">
      <a href="${esc(nav.instagram)}" class="jtn-icon" target="_blank" rel="noopener noreferrer" aria-label="Instagram">${ICON.ig}</a>
      <a href="${tel}" class="jtn-contact" aria-label="Call us">${ICON.phone}<span><b>Talk to a Real Person</b>${esc(nav.phone.display)}</span></a>
      ${/* Text Us opens the Tawk messenger on every device (assets/js/site-nav.js);
            Talk to a Real Person always dials (owner, 2026-10-02). */ ''}<a href="${sms}" class="jtn-contact" aria-label="Text us">${ICON.text}<span><b>Text Us</b>Fast reply</span></a>
      <a href="${esc(nav.account.href)}" class="jtn-icon jtn-ico-acct" aria-label="${esc(nav.account.label)}">${ICON.user}</a>
      <a href="${esc(nav.cart.href)}" class="jtn-icon jtn-ico-cart" aria-label="${esc(nav.cart.label)}">${ICON.cart}</a>
      <a href="${esc(abs(nav.quote.href))}" class="jtn-quote">${esc(nav.quote.label)}</a>
      <button type="button" class="jtn-burger" aria-label="Open menu" aria-expanded="false" aria-controls="jtn-drawer"><span></span><span></span><span></span></button>
    </div>
  </div>
</div>
<div class="jtn-shade" hidden></div>
<div class="jtn-drawer" id="jtn-drawer" hidden>
  <div class="jtn-drawer-h"><b>Menu</b><button type="button" class="jtn-close" aria-label="Close menu">&#x2715;</button></div>
  <div class="jtn-drawer-nav">
    ${drawer}
  </div>
  <div class="jtn-drawer-nav jtn-drawer-me"><a href="${esc(nav.cart.href)}">🛒 ${esc(nav.cart.label)}</a><a href="${esc(nav.account.href)}">👤 ${esc(nav.account.label)}</a></div>
  <div class="jtn-drawer-cta">
    <a href="${esc(nav.design.href)}" class="jtn-btn" data-from="nav">${esc(nav.design.label)}</a>
    <a href="${esc(abs(nav.quote.href))}" class="jtn-btn jtn-btn-2">${esc(nav.quote.label)}</a>
    <a href="${tel}" class="jtn-btn jtn-btn-2">📞 ${esc(nav.phone.display)}</a>
  </div>
</div>
<script src="${abs('/assets/js/site-nav.js')}" defer></script>
${END}`;
}

/* The end of the element that opens at `from` (same tag, nesting counted). */
function elementEnd(html, from) {
  const tag = html.slice(from + 1).match(/^[a-zA-Z0-9]+/)[0].toLowerCase();
  const re = new RegExp(`<(/?)${tag}\\b[^>]*>`, 'gi');
  re.lastIndex = from;
  let depth = 0, m;
  while ((m = re.exec(html))) {
    depth += m[1] ? -1 : 1;
    if (depth === 0) return m.index + m[0].length;
  }
  throw new Error(`unclosed <${tag}> at ${from}`);
}

/* The old, per-page copies of the menu, removed on a page's first --write. */
const OLD = [
  /<div class="announcement-bar"[^>]*>/i,
  /<header\b[^>]*>/i,
  /<div class="drawer-overlay"[^>]*>/i,
  /<div class="mobile-drawer"[^>]*>/i,
];

function applyReviews(html, rel) {
  if (NO_REVIEWS.has(rel)) return html;
  if (html.includes(RS)) {
    const a = html.indexOf(RS), b = html.indexOf(RE, a) + RE.length;
    html = html.slice(0, a) + REVIEWS_BLOCK + html.slice(b);
  } else {
    const f = html.search(/<footer\b/i);
    if (f === -1) return html;
    const lineStart = html.lastIndexOf('\n', f) + 1;
    html = html.slice(0, lineStart) + REVIEWS_BLOCK + '\n' + html.slice(lineStart);
  }
  if (!html.includes(REVIEW_CSS_TAG)) html = html.replace('</head>', `  ${REVIEW_CSS_TAG}\n</head>`);
  return html;
}

function apply(html, block) {
  if (html.includes(START)) {
    const a = html.indexOf(START), b = html.indexOf(END, a) + END.length;
    html = html.slice(0, a) + block + html.slice(b);
  } else {
    let at = -1;
    for (const re of OLD) {
      const body = html.indexOf('<body');
      const m = re.exec(html.slice(body));
      if (!m) continue;
      const s = body + m.index;
      // Swallow the comment that labelled it, if any, and the line it sat on.
      let start = s;
      // Swallow the comments that labelled it ("<!-- Header -->"), if any.
      for (;;) {
        const c = html.slice(0, start).match(/[ \t]*<!--[^>]*-->\s*$/);
        if (!c || !/announcement|header|drawer/i.test(c[0])) break;
        start -= c[0].length;
      }
      const end = elementEnd(html, s);
      if (at === -1 || start < at) at = start;
      html = html.slice(0, start) + '\u0000NAV\u0000' + html.slice(end);
    }
    // Every removed piece became a placeholder; the first gets the menu.
    const first = html.indexOf('\u0000NAV\u0000');
    if (first === -1) {
      const m = html.match(/<body[^>]*>/i);
      html = html.replace(m[0], m[0] + '\n' + block);
    } else {
      html = html.slice(0, first) + block + html.slice(first + 5).split('\u0000NAV\u0000').join('');
    }
  }
  if (!html.includes(CSS_TAG)) html = html.replace('</head>', `  ${CSS_TAG}\n</head>`);
  return html;
}

function run(mode) {
  const nav = JSON.parse(fs.readFileSync(NAV, 'utf8'));
  const block = render(nav);
  const drifted = [];
  /* The Design Studio's copy: same menu, absolute links. design.jtees.net
     fetches this file (jt-site-nav.php) and keeps a copy in its repo. */
  const snippetFile = path.join(PUBLIC, 'assets', 'data', 'site-nav.html');
  const snippet = render(nav, 'https://www.jtees.net') + '\n';
  if (!fs.existsSync(snippetFile) || fs.readFileSync(snippetFile, 'utf8') !== snippet) {
    drifted.push('assets/data/site-nav.html');
    if (mode === 'write') fs.writeFileSync(snippetFile, snippet);
  }
  for (const rel of pages()) {
    const file = path.join(PUBLIC, rel);
    const before = fs.readFileSync(file, 'utf8');
    const after = applyReviews(apply(before, block), rel);
    if (after !== before) {
      drifted.push(rel);
      if (mode === 'write') fs.writeFileSync(file, after);
    }
  }
  return drifted;
}

module.exports = { render, apply, applyReviews, pages, run, START, END, RS, NO_REVIEWS };

if (require.main === module) {
  const mode = process.argv.includes('--write') ? 'write' : 'check';
  const changed = run(mode);
  if (mode === 'write') console.log(`menu written into ${changed.length} page(s)`);
  else if (changed.length) { console.log('menu out of date on:\n  ' + changed.join('\n  ') + '\nrun: node tools/site-nav.js --write'); process.exit(1); }
  else console.log('every page has the current menu');
}
